openapi: 3.0.3
info:
  version: 1.0.0
  title: Api Classroom
servers:
  - url: http://localhost:8080
    description: Desenvolvimento
  - url: http://api
    description: Produção
externalDocs:
  description: Documentação
  url: https://documentação

tags:
  - name: materials
    description: Teaching materials
paths:
  /marerials/{codigoTurma}:
    post:
      summary: Add some matirials
      operationId: post-marerials
      parameters:
        - in: path
          description: codigo da turma
          name: codigoTurma
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/material'

      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: string

components:
  schemas:
    material:
      type: object
      additionalProperties: false
      properties:
        title:
          type: string
          maxLength: 20
#          nullable: true
#        file:
#          type: string
#          format: binary